name: Telegram Notifier
description: Send message to Telegram
inputs:
  message:
    description: Telegram message to send
    required: true

runs:
  using: composite
  steps:
    - name: Send Telegram Message
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.DESK_TELEGRAM_BOT }}/sendMessage" \
          -d chat_id="${{ secrets.MUSASHINO_GROUP_ID }}" \
          -d text="${{ inputs.message }}" \
          -d parse_mode=Markdown
      shell: bash
