name: Android CI

on:
  pull_request:
    branches: [ aboba ]

jobs:

  build:
    uses: ./.github/workflows/build.yml

  run-unit-tests:
    needs: build
    uses: ./.github/workflows/run-unit-tests.yml

  run-lint:
    needs: build
    uses: ./.github/workflows/run-lint.yml

  run-instrumentation-tests:
    needs: build
    uses: ./.github/workflows/run-instrumentation-tests.yml

  send-results:
    needs: [ build, run-unit-tests, run-lint, run-instrumentation-tests ]
    if: always()
    uses: ./.github/workflows/send-results.yml
