name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    uses: ./.github/workflows/steps/build.yml

  run-unit-tests:
    needs: build
    uses: ./.github/workflows/steps/run-unit-tests.yml

  run-lint:
    needs: build
    uses: ./.github/workflows/steps/run-lint.yml

  run-instrumentation-tests:
    needs: build
    uses: ./.github/workflows/steps/run-instrumentation-tests.yml

  send-results:
    needs: [ build, unit-tests, lint, instrumentation-tests ]
    uses: ./.github/workflows/steps/send-results.yml
    if: always()