name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  run-unit-tests:
    needs: build
    uses: ./.github/workflows/run-unit-tests.yml

  run-lint:
    needs: build
    uses: ./.github/workflows/run-lint.yml

  run-instrumentation-tests:
    needs: build
    uses: ./.github/workflows/run-instrumentation-tests.yml

  send-results:
    needs: [ build, run-unit-tests, run-lint, run-instrumentation-tests ]
    uses: ./.github/workflows/send-results.yml
    if: always()
    secrets: inherit
    with:
      build_result: ${{ needs['build'].result }}
      unit_result: ${{ needs['run-unit-tests'].result }}
      lint_result: ${{ needs['run-lint'].result }}
      instr_result: ${{ needs['run-instrumentation-tests'].result }}