name: Notify Telegram

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram message
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.DESK_TELEGRAM_BOT }}
        TELEGRAM_CHAT_ID: ${{ secrets.MUSASHINO_GROUP_ID }}
        TELEGRAM_MESSAGE: ${{ inputs.message }}
      run: |
        echo "::debug::TOKEN=${TELEGRAM_BOT_TOKEN}, CHAT_ID=${TELEGRAM_CHAT_ID}, MESSAGE=${TELEGRAM_MESSAGE}"
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
             -d chat_id="${TELEGRAM_CHAT_ID}" \
             -d text="${TELEGRAM_MESSAGE}" \
             -d parse_mode=Markdown
