name: Notify Telegram

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.DESK_TELEGRAM_BOT }}
          TELEGRAM_CHAT_ID: ${{ secrets.MUSASHINO_GROUP_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
               -d chat_id="${TELEGRAM_CHAT_ID}" \
               -d text="${{ inputs.message }}" \
               -d parse_mode=Markdown
