name: Run Instrumentation Tests
on:
  workflow_call:

jobs:
  instrumentation-tests:
    name: Run Instrumentation Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-android

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: app/build/
        continue-on-error: true

      - name: Run instrumentation tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel
          emulator-options: -no-window -no-audio -no-boot-anim
          script: ./gradlew connectedDebugAndroidTest

      - name: Publish Instrumentation Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Instrumentation Test Results
          path: app/build/outputs/androidTest-results/**/*.xml
          reporter: java-junit
          fail-on-error: true
          list-tests: failed
          list-suites: failed

      - name: Upload instrumentation test reports
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-report
          path: |
            app/build/outputs/androidTest-results/
