name: Run unit tests
on:
  workflow_call:

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-android

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: app/build/
        continue-on-error: true

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Publish unit test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: app/build/test-results/testDebugUnitTest/
          reporter: java-junit
          fail-on-error: true

      - name: Upload unit test reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: |
            app/build/reports/tests/testDebugUnitTest/
