name: Run Android Lint
on:
  workflow_call:

jobs:
  run-lint:
    name: Run Android Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-android

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: app/build/
        continue-on-error: true

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Publish Lint Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Android Lint Results
          path: app/build/reports/lint-results-debug.xml
          reporter: android-lint
          fail-on-error: true

      - name: Upload lint reports
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: |
            app/build/reports/lint-results-debug.html
      