name: Form message and send

on:
  workflow_call:
    inputs:
      build_result:
        required: true
        type: string
      unit_result:
        required: true
        type: string
      lint_result:
        required: true
        type: string
      instr_result:
        required: true
        type: string
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
      actor:
        required: true
        type: string

jobs:
  form-message:
    name: Form message to send
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.format.outputs.message }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format Telegram message
        id: format
        run: |
          escape_markdown() {
            echo "$1" | sed -E 's/([*_`\[])/\\\1/g'
          }
        

          BUILD_RESULT=$(escape_markdown "${{ inputs.build_result }}")
          UNIT_RESULT=$(escape_markdown "${{ inputs.unit_result }}")
          LINT_RESULT=$(escape_markdown "${{ inputs.lint_result }}")
          INSTRUMENTATION_RESULT=$(escape_markdown "${{ inputs.instr_result }}")
          RUN_URL="https://github.com/${{ inputs.repo }}/actions/runs/${{ github.run_id }}"
          
          REPO_NAME=$(escape_markdown "${{ inputs.repo }}")
          BRANCH_NAME=$(escape_markdown "${{ inputs.branch }}")
          ACTOR=$(escape_markdown "${{ inputs.actor }}")

          if [[ "$BUILD_RESULT" == "success" && "$UNIT_RESULT" == "success" && "$LINT_RESULT" == "success" && "$INSTRUMENTATION_RESULT" == "success" ]]; then
            EMOJI="✅"
          elif [[ "$BUILD_RESULT" == "failure" || "$UNIT_RESULT" == "failure" || "$LINT_RESULT" == "failure" || "$INSTRUMENTATION_RESULT" == "failure" ]]; then
            EMOJI="❌"
          elif [[ "$BUILD_RESULT" == "cancelled" || "$UNIT_RESULT" == "cancelled" || "$LINT_RESULT" == "cancelled" || "$INSTRUMENTATION_RESULT" == "cancelled" ]]; then
            EMOJI="🚫"
          else
            EMOJI="⚠️"
          fi

          MESSAGE=$(cat <<EOF
          ${EMOJI} *Android CI completed*
          
          🔧 *Build*: $BUILD_RESULT
          🧪 *Unit Tests*: $UNIT_RESULT
          🧹 *Lint*: $LINT_RESULT
          📱 *Instrumentation*: $INSTRUMENTATION_RESULT
          ───────────────────────────────
          📦 *Repo*: $REPO_NAME
          🌿 *Branch*: $BRANCH_NAME
          🙋 *Triggered by*: $ACTOR
          ───────────────────────────────
          🔗 [Open in GitHub Actions](${RUN_URL})
          EOF
          )

          MESSAGE=$(echo "$MESSAGE" | head -c 3900)

          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  notify-tg:
    name: Send Telegram message
    uses: ./.github/workflows/notify-telegram.yml
    needs: form-message
    with:
      message: ${{ needs.form-message.outputs.message }}
    secrets: inherit
